(* Core *)
root = statement*
statement = token (<empty> token)*

<token> = keyword | !keyword (elem | list) | assign
<term> = [<empty>] number | [<'('>] add-sub [<')'>] [<empty>]
<atom> = [<empty>] keyword init [<empty>]
<elem> = [<empty>] atom | term | pair | identifier [<empty>]
list = [<empty>] <'['>(elem [<','> elem])* <']'> [<empty>]
pair = term <'->'> (elem | list) [<empty>,<empty>]
assign = identifier <'='> (atom | list)
identifier = [<empty>] #':[a-zA-Z]+' [<empty>]
init = keyword <'('> identifier* <')'> [<empty>]
keyword = [<empty>] #'Loop|Note|Scale|Chord|Rest|Times|Forever' [<empty>]
empty = #'\s+'
word = letter+
number = digit+
<letter> = #'[a-zA-Z]'
<digit> = #'[0-9]'

(* Math *)
<add-sub> = mul-div | add | sub
add = [<empty>] add-sub [<empty>] <'+'> [<empty>] mul-div [<empty>]
sub = [<empty>] add-sub [<empty>] <'-'> [<empty>] mul-div [<empty>]
<mul-div> = term | mul | div
mul = mul-div <'*'> term
div = mul-div <'/'> term